FROM docker.io/library/debian:13 AS dev
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update && apt-get install -y expect unzip && apt-get clean
COPY downloads/ /downloads/
ADD installer.expect /
RUN chmod +x /downloads/*run /installer.expect && mkdir -p /opt && ln -s /downloads/xc8*run /xc8.run && /installer.expect
ADD unpacker.sh /
#WORKDIR /downloads/packs
RUN chmod +x /unpacker.sh && /unpacker.sh

FROM docker.io/library/debian:13 AS result
RUN apt-get -y update && apt-get install -y make unzip zip && apt-get clean
COPY --from=dev /opt /opt
RUN /usr/sbin/useradd developer
USER developer
VOLUME /app
WORKDIR /app
CMD "/bin/bash"
